---
title: "Assignment 4"
linktitle: "# 4"
date: "6/16/2020"
due_date: "2022-02-22"
due_time: "11:30am"
output:
  blogdown::html_page:
    css: "/slides/css/additionalCols.css"
menu:
  assignment:
    parent: Assignments
    weight: 4
type: docs
weight: 5
editor_options: 
  chunk_output_type: console
---

## Instructions
This assignment is all about making figures. It's going to be a bit free-form because when it comes to making figures, there are a *silly* number of options. Here are the conditions:

- You must use the `ggplot2` package and syntax. This should *not* be practice for `base R`.
- Your choice of variables must make sense for the type of plot you are making. That is, don't give me a histogram for a dichotomous variable (that would just be 2 bars and super weird).
- All figures must follow the basics of clear axis labels and titles! (*please* don't make me take points off for this...). **I will take points off if these are missing or not clear!**
- NO PIE CHARTS!

## Visualizing data in different ways

:::list
Here's your to-do list:

Pick 2 variables from your dataset. Make *3 __different__ figures* that show the relationship between these 2 variables. Your figures must include the following:

  - A theme
  - Make use of different colors (manually or with a color palette)
  - You need to pick the best of the 3 figures **and explain why you think this is the case**
  - After you've picked your favorite, add a 3rd *variable* (not `geom`) to that plot (just to your favorite plot -- not to all 3 plots). You can choose the dimension on which to add the 3rd variable (aka which aesthetic). Did adding the 3rd variable enhance this plot or does it detract? Explain why.
:::
  
## Explanation vs. Clutter
:::list
Here's your to-do list:

- Make a plot that uses at least 3 `geom`s. Make it as beautiful, publication-ready as you can.
- Explain whether the extra `geom`s help explain your data or if it just clutters everything up. You may add an additional plot if you think it help explains your answer better (e.g., if you think a plot with only 2 `geom`s would be better, make that plot). An extra plot is not required. The explanation is required.
:::

### Yahhoooooooo!
We'll talk more about the theory of data viz later in the semester. But for now, you should feel comfortable plotting in the `ggplot2` world. 

Go ahead and submit your code file to Canvas. If you used an outside dataset, please also submit that, too.
