main:
  - name: How This Works
    url: /welcome/
    weight: 1
  - name: Lectures
    url: /lectures/
    weight: 2
  - name: Practice
    url: /practice/
    weight: 3

lectures:
  - name: Overview
    weight: 1
  - name: The Basics
    weight: 2
  - name: Tidyverse
    weight: 3
  - name: Reproducibility
    weight: 4
  - name: Data Viz
    weight: 5

practice:
  - name: Overview
    weight: 1
  - name: The Basics
    weight: 2
  - name: Tidyverse
    weight: 3
  - name: Reproducibility
    weight: 4
  - name: Data Viz
    weight: 5
