main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Lectures
    url: /lectures/
    weight: 3
  - name: Practice
    url: /practice/
    weight: 4
  - name: Assignments
    url: /assignments/
    weight: 5

lectures:
  - name: Overview
    weight: 1
  - name: The Basics
    weight: 2
  - name: Tidyverse
    weight: 3
  - name: Reproducibility
    weight: 4
  - name: Data Viz
    weight: 5
  - name: Statistics
    weight: 6
  - name: Advanced Topics
    weight: 7
practice:
  - name: Overview
    weight: 1
  - name: The Basics
    weight: 2
  - name: Tidyverse
    weight: 3
  - name: Reproducibility
    weight: 4
  - name: Data Viz
    weight: 5
  - name: Statistics
    weight: 6
  - name: Advanced Topics
    weight: 7
assignment:
  - name: Overview
    weight: 1
  - name: Assignments
    weight: 2
  - name: Quizzes
    weight: 3
  - name: Mini Assignments
    weight: 4