---
title: "Syllabus"
slug: syllabus
output: 
  html_document:
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
---

## What is this class?
- Applied Statistical Analysis with R (Psych 3175)
- Monday/Wednesday 8:30am-9:50am
- Eads Room 115

## Who are we?

Instructor: **Shelly Cooper, PhD (she/her)** [shelly.cooper@wustl.edu](mailto:shelly.cooper@wustl.edu).

Assistant to the Instructor: **Derek Simon (he/they)** [d.a.simon@wustl.edu](mailto:d.a.simon@wustl.edu).

## What's the course philosophy?
Programming & statistics are in demand skills across a wide variety of fields, including psychology, neuroscience, and other related disciplines. The goal of this course is for you to feel comfortable with the programmatic skills needed to take a data analysis project from start to finish including data wrangling, executing appropriate statistical tests, interpreting the results, and communicating your findings. Although we will use `R` software, the core concepts should carry with you to other programming languages (Python, MATLAB etc.).

You do not need to have any experience with programming, at all, in order to do well in this class.

>The only difference between a beginner and expert programmer, is that the expert is better at Googling”.

*The goal of this course is to get you to the point where you can effectively Google `R`-related questions and mostly understand the results.* 

## What will you learn in this class?
Learning Objectives:

  -	The fundamentals of programming with R statistical software. This includes objects, data classes, functions, data wrangling, plotting/graphing, and making reproducible reports
  -	The fundamentals of basic statistics including distributions, correlations, t-tests, ANOVAs, and linear regression
  -	A knowledge base in which to expand your statistical horizons by using more sophisticated code, such as bootstrapping and writing your own functions (make your code work for you!)

## How is this course organized?
There will be 3 units:

  1.	Getting you up to speed with coding in R. 
  2.	Recap of statistics learned in Psych 300 (Intro to Psych Stats). However, the material will focus on the application of these tests in R, accessing their results, and incorporating them into academic manuscripts.
  3.	More advanced topics in terms of writing code that can expand your statistical horizons. 
  
This is a **flipped** classroom meaning your homework is to watch the lectures. Our in-class time will be dedicated to hands-on problem sets. For a roadmap of the class, please see the [Schedule](https://psych4175.profcoops.com/schedule/) page of this website.
  
## What do you need for this course?
You'll need 4 things:

  1. You need `R` and it's buddy `RStudio`. We will go through this together.
  2. You need this website -- most of the content will take place on this website.
  3. While not required, I **very strongly** suggest being apart of our Slack workspace. You can quickly and easily ask the instructors questions privately or publicly so your peers can learn too. You can interact with your peers, and enjoy remarkably silly memes. 
  4. Our Canvas page will contain your grades, datasets, and will be where you complete your peer code reviews.
  
## How do I get a good grade?
There are no exams! Hooray! To get a good grade in this class, you need to do the following:

  - **Assignments** will be posted on the course website. These are mostly weekly assignments, and they are there to make sure you get lots of practice.
      - The first 8 assignments will be completed on your own
      - The remaining 3 assignments will be completed with peers
  - **Peer Reviews** will give you practice looking at other peoples' code and will give you consistent feedback from someone other than the instructor/AI. You will be randomly assigned to a peer in your class and you will answer very specific questions about the assignment.
  - **Final Project** You will complete a final take-home project due during finals week (if you want to turn it in before then, that’s OK!). This project will be completely `R`-based, and will incorporate skills learned over the semester with extra emphasis on those learned in Unit 3. This will be completed on your own. 
  - **Participation** refers to answering questions in class. This is to keep you honest about watching lectures at home (see [Schedule](https://psych4175.profcoops.com/schedule/) page for more details). 
    

\begin{equation}
\begin{aligned}

\text{Solo Assignments 8 x 15 pts/ea = 120pts} \\
\text{Peer Reviews 8 x 5pts/ea = 40pts} \\
\text{Group Assignments 3 x 15pts/ea = 45pts} \\
\text{Final Project 1 x 25pts/ea = 25pts} \\
\text{Participation 15 (adjusted) x 1.5pts/ea = 20pts} \\
\mathbf{\text{Total = 250pts}}

\end{aligned}
\end{equation}


## Final Grade Rubric

\begin{equation}
\begin{split}

& \text{> 93% = A} \\
& \text{90% - 92.99% = A-} \\
& \text{87% - 89.99% = B+} \\
& \text{83% - 86.99% = B} \\
& \text{80% - 82.99% = B-} \\
& \text{77% - 79.99% = C+} \\

\end{split}

\begin{split}
& \text{73% - 76.99% = C} \\
& \text{70% - 72.99% = C-} \\
& \text{67% - 69.99% = D+} \\
& \text{63% - 66.99% = D} \\
& \text{60% - 62.99% = D-} \\
&\text{< 50% = F}

\end{split}
\end{equation}

## What to Expect?

#### You will struggle a lot, and you will learn a lot
Learning to code is a lot like learning to snowboard or surf. The beginning is hard. You fall down a lot. But once you get the feel of things, it becomes much easier! Most students find that the first 7 weeks are the most difficult of the course because they are learning this new thing and "falling down". This is totally normal! We are here to help you. But make no mistake, learning this content can be challenging and requires a lot of work. The course is designed to facilitate your learning, and make sure you don't fall too far behind. **Procrastination is not your friend!** Those who take the perspective of doing a little bit each day will be the most successful. 

#### Late Adds
Please be aware that if you decide to join this course after Week 2, you will need to make up a lot of work very quickly. In general, I don’t advise students to add the course more than 4 class sessions late. If you are thinking about adding the class late, I encourage you to contact me first. We might decide together that it would be better for you to wait to take this class, in which case the good news is that it will be offered again in Fall 2026!

## Class Policies

#### Attendance
Your attendance, whether in person or online, is required for you to do well in the course. You get **2** unexcused absences for the semester. For these, you do not need to tell the instructor anything. Any other absences must be excused by the instructor. Excused absences include illness, bereavement etc. The instructor has full authority to decide what is excused and what is unexcused.

Attendance is wrapped up in the participation portion of your grade. All unexcused absences, beyond the 2 that are permitted, will be counted as a 0 for that day's participation grade.

#### Late Assignments
One of the most important aspects of this class is staying on top of your work -- you cannot progress your skills if you haven't mastered the basics. These policies are designed to motivate you to stay on track.

You will be docked points based on how late your work is turned in. This is true for both homework assignments and peer review assignments. Here is the rubric for how many points will be docked:

- 5% for within first 24 hours
- 10% for 2 days late
- 15% for 3 days late
- 20% for 4 days late
- 25% for 5 days late

After 5 days, if you still have not completed the assignment, you will receive a 0. 

#### Artifical Intelligence (Chat-GPT etc.) Policy
New Artificial Intelligence tools like Chat-GPT are rapidly changing the landscape of how we write code. These tools are truly wonderful for writing code quickly. It is used frequently outside of the classroom for writing code in a variety of languages, including R. It would be CRAZY not to incorporate this tool into your learning.

That said, Chat-GPT very, very often gives you the *WRONG* code. My goal is to get you to a place where you can use Chat-GPT and be able to understand if the code it provides will give you the right answer or the wrong one. Here is my policy for this class:

- You are allowed to use AI tools, however, this is contingent on you providing the link to the "conversation". This way, I can help make sure you understand why the code works or does not work. **If you do not provide this link, and you still use AI tools, it will be considered an academic integrity violation.**

- I very, very strongly encourage you to *NOT* use Chat-GPT until midway through the semester. The first part is hard, but you'll need to know these topics in order to use Chat-GPT as an effective tool. We will devote an entire class to using Chat-GPT. But it is my opinion that you are sort of shooting yourself in the foot if you try to use it without understanding some of the basic principles. 

## Staying Connected
Learning to code can be really scary -- impostor syndrome is real! The best thing we can do to combat these feelings is to stay connected to one another. Here's how we'll accomplish this in our class:

-	Your peer review will be with the same person! This way, you will get to know your buddy over the course of the semester. Make a friend! 

-	We will have a dedicated class Slack workspace (see homepage of website for link). You can post questions that everyone can see, or make use of direct messaging. The instructors will respond to your questions on Slack (if your peers don't respond first!). This is really great for one-off questions, or need some quick clarification on. We will also have a dedicated channel for silly programming and stats memes, because humor is important when you're learning a skill like coding, in which you’ll repeatedly fail. Slack is not required *per se*, but it is **highly encouraged**.

## Let's learn from COVID-19
COVID sucked. But instead of burying our heads in the sand and forgetting it existed, let's at least extract some things and incorporate them into our lives. For this class, here's what that means:

- It is OK to not be OK. If you tell me you're having trouble, I'm not going to judge you or think less of you. I hope you will do the same for me. I will work with you to make sure we have a reasonable plan in place should something come up. *However*, this does require you telling me "hey, I'm not OK".
- You are always welcome to come talk to me about things that you're going through. If I can't help you, I usually know someone who can help -- or I can at least give you some resources and point you in the right direction.
- If you are struggling or need extra help, please just ask. I promise I will work with you.


### Online Etiquette
There will be a lot of online communication with the instructor, the AI, and your peers. You are expected to maintain a polite and respectful tone in their online discourse. Some things to consider:

  -	Any communication shared privately may become public, so be mindful of what you share in discussion boards or chats. This is especially true for sharing any personal and/or identifying information about you or someone else. Do not share any passwords or divulge any personal information (yours or others) that can be used in a malicious manner (phone numbers, addresses etc.).
  -	Humor doesn't always translate in an online forum. If you want to make a joke or a sarcastic remark, be 100% sure that it is clear you are joking. 
  -	Your comments must be readable to everyone, therefore I ask that you please refrain from using shortcuts. For example, please type out “you” instead of “u”. Very common acronyms are OK (“lol” or “haha”). But please refrain from acronyms that are not as well-known (“fwiw” etc.).
  -	Treat your classmates, professor, and AI with kindness and respect. Any indication of online harassment or bullying will not be tolerated and will be reported. This is especially pertinent when giving constructive feedback in code reviews.
  - Please avoid using ALL CAPS because it can be interpreted as yelling.

### Academic Policies & Resources
- [University Code of Conduct](https://wustl.edu/about/compliance-policies/academic-policies/university-student-judicial-code/)
  - Any student found guilty of academic misconduct, such as cheating, plagiarizing, forgery, or furnishing false information to a University official will be subject to consequences including failing the class, suspension from the University, or expulsion from the University.
  - As a reminder, AI tools are permitted with proper citation. If you have any questions about what is and what is not authorized usage, please speak with the instructor. 
  
-	Special accommodations (such as a learning, sensory, or physical disability or any other diagnosis that requires special accommodations and/or assistance with lectures, reading, written assignments, and/or exam taking)
    - Contact [Disability Resources](https://students.wustl.edu/disability-resources/) at [disabilityresources@wustl.edu](mailto:disabilityresources@wustl.edu) or call 314-935-5970
    - Please contact me as soon as possible if you need special accommodations. Once I have the Accommodation Letter from Disability Resources, we can discuss ways to modify the course experience for you. 
  
-	Mental & Physical Health:
    - [Habif Health and Wellness Center](https://students.wustl.edu/habif-health-wellness-center/), email [HabifInfo@wustl.edu](mailto:HabifInfo@wustl.edu) or call 314-935-6666
  
-	WUSTL Police Department
    - On campus emergency, please call 314-935-5555
  
-	Relationship or sexual violence, including sexual harassment and stalking
    - Contact a licensed [RSVP](https://students.wustl.edu/relationship-sexual-violence-prevention-center/) counselor (confidential, with some limited information being shared as needed with the appropriate university administrator) at [rsvpcenter@wustl.edu](mailto:rsvpcenter@wustl.edu) or call 314-935-3445
    - Contact the University’s Title IX Director, Ms. Jessica Kennedy, at [jwkennedy@wustl.edu](mailto:wkennedy@wustl.edu) or call 314-935-3118
    -	*PLEASE NOTE* You can always come talk to me. Period. However, if you come to me with any issues surrounding child abuse, suicidal tendencies, or sexual assault, sexual discrimination, sexual harassment, dating violence, domestic violence or stalking, I am required to report these to their appropriate administrators. Washington University faculty and administrators strive to maintain confidentiality, but some information may need to be disclosed when it is a matter of safety. 



