---
title: "Assignment 5"
linktitle: "# 5"
date: "6/16/2020"
due_date: "2020-10-20"
due_time: "2:30pm"
output:
  blogdown::html_page:
    css: "/slides/css/additionalCols.css"
menu:
  assignment:
    parent: Assignments
    weight: 5
type: docs
weight: 5
editor_options: 
  chunk_output_type: console
---

## Instructions
This assignment is all about making figures. It's going to be a bit free-form because when it comes to making figures, there are a *silly* number of options. Here are the conditions:

- You must use the `ggplot` package and syntax. This should *not* be practice for `base R`. - Your choice of variables must make sense for the type of plot you are making. 
- All figures must follow the basics of clear axis labels and titles! (*please* don't make me take points off for this...)
- NO PIE CHARTS!

:::note
**Note**: Please use a RNotebook for this assignment:

- There are two main "sections". Make sure they each have an appropriate header
- All code must be contained within a code chunk. You are allowed to split up your code into many code chunks, or just have one large one per section. That is up to you. However, I do not want to see the code for an entire figure located outside of a chunk. 
- Any explanations I ask for should be *outside* of a code chunk (aka formatted text). I personally would put this directly underneath the header, but it can come after the code chunk ends, as well. Whatever you prefer. However, I do not want to see any sentences as comments within a code chunk (e.g., `#a long sentence like this`). Comments within the code is fine in terms of describing what the code is doing. But when I ask for your opinion or an explanation of something, that needs to be formatted text. 
:::

## Visualizing data in different ways

:::list
Here's your to-do list:

Pick 2 variables from your dataset. Make *3 __different__ figures* that show the relationship between these 2 variables. Your figures must include the following:

  - A theme
  - Make use of different colors (manually or with a color palette)
  - You need to pick the best of the 3 figures **and explain why you think this is the case**
  - After you've picked your favorite, add a 3rd *variable* (not `geom`) to that plot (just to your favorite plot -- not to all 3 plots). You can choose the dimension on which to add the 3rd variable (aka which aesthetic). Did adding the 3rd variable enhance this plot or does it detract? Explain why.
:::
  
## Explanation vs. Clutter
:::list
Here's your to-do list:

- Make a plot that uses at least 3 `geom`s. Make it as beautiful, publication-ready as you can.
- Explain whether the extra `geom`s help explain your data or if it just clutters everything up. You may add an additional plot if you think it help explains your answer better (e.g., if you think a plot with only 2 `geom`s would be better, make that plot). An extra plot is not required. The explanation is required.
:::

### Yahhoooooooo!
We'll talk more about the theory of data viz later in the semester. But for now, you should feel comfortable plotting in the `ggplot` world. 

Go ahead and submit your `.Rmd` and `.html` file to Canvas. If you used an outside dataset, please also submit that, too.
